CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate) 
VALUES('Hacer una aplicación', 2, 'Usando C++', '2019-11-20');

INSERT INTO tasks(name, done, projectId) VALUES('Descargar VueJS', false, 1);

INSERT INTO tasks(name, done, projectId) VALUES('Crear UI Web', false, 1);
INSERT INTO tasks(name, done, projectId) VALUES('Descargar flutter', false, 2);
INSERT INTO tasks(name, done, projectId) VALUES('Diseñar UI', false, 2);